#!/bin/bash

mkdir -p Documents/projects/lab19/using/simple/bash/commands
cd Documents/projects/lab19/using/simple/bash/commands
sleep 60
suz=$(ls -a | grep -o '[0-9a-zA-Z]\{28\}')
echo "Flag is: $suz"

